### ISSUE TITLE
Install with homebrew?

### ISSUE THREAD

**Issue by hurrymaplelad** [icefox/git-hooks#49]
I usually install this sort of thing on OSX with homebrew.  It took me a while to figure out this is possible with 

```
$ brew install --HEAD homebrew/head-only/git-hooks
```

Would you take a PR to add this to the README?

**Comment by zbeekman** [comment]
+1

**Comment by Zearin** [comment]
:+1:

**Comment by Zearin** [comment]
@icefox ping

**Comment by GonZo** [comment]
:+1:

**Comment by molovo** [comment]
git-hooks has been in homebrew/core for a while now, so closing this issue.
