### ISSUE TITLE
Build new release, update Homebrew formula

### ISSUE THREAD

**Issue by MitchLillie** [icefox/git-hooks#65]
I took a chance with `brew install git-hooks` and then noticed that the tarball v1.00.0 is from 2013.

Any reason not to put out a new minor release with the changes since then? Happy to send a PR for this.

**Comment by icefox** [comment]
Project has never had a release and I didn't package up that tarball... so if you want you are free to make a new package for brew?

**Comment by icefox** [comment]
Haha there was a release "tag", but I think i might have just been testing the tag hook?  Honestly I don't  remember.  But yeah feel free to make a package of head

**Comment by MitchLillie** [comment]
Well, it's being referenced [here](https://github.com/Homebrew/homebrew-core/blob/master/Formula/git-hooks.rb). I guess I can fork it, build a release on my fork and then send a PR to point that Homebrew formula to my fork, but that doesn't really seem fair. Alternately you could build a new release on this repo and I'll send a PR to update the formula?
