### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by janosh** [icefox/git-hooks#68]
Is this project dead?

**Comment by icefox** [comment]
Unmaintained, do you want to fork it and take over ownership?  I'll delete this repository if you do.

**Comment by janosh** [comment]
Sorry, I don't think I'm a good enough shell scripter to take over. I just thought this looks like a cool project with lots of potential, especially the part about [sharing hooks from multiple locations](https://github.com/icefox/git-hooks#locations).
